# INFO: NixOS module to trust .NET development certificates system-wide.

{
  config,
  lib,
  ...
}:

with lib;
{
  options.snowfall.security.dotnetCerts = {
    enable = mkOption {
      type = types.bool;
      default = false;
      description = ''
        Trust .NET development certificates system-wide.

        Certificates are generated by the home-manager dotnet module
        and stored in ~/.aspnet/dev-certs/https/
      '';
    };

    users = mkOption {
      type = with types; listOf str;
      default = [ ];
      description = ''
        List of users whose .NET development certificates should be trusted.
      '';
    };
  };

  config = mkIf config.snowfall.security.dotnetCerts.enable {
    security.pki.certificates =
      let
        inherit (config.snowfall.security.dotnetCerts) users;
        # Read certificate files for each user
        certFiles = map (
          user:
          let
            certPath = "/home/${user}/.aspnet/dev-certs/https/aspnetcore-localhost.crt";
          in
          if builtins.pathExists certPath then builtins.readFile certPath else ""
        ) users;
        # Filter out empty certificates
        validCerts = filter (cert: cert != "") certFiles;
      in
      validCerts;
  };
}
