# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/b3c43889-ddf4-4bc4-a076-3a4a6dbe200d";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-7a6cd24d-f554-4747-a64e-f93b0e0b5d46".device = "/dev/disk/by-uuid/7a6cd24d-f554-4747-a64e-f93b0e0b5d46";

  boot.supportedFilesystems = [ "ntfs" ];

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/FF2B-2808";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  fileSystems."/run/media/games" = {
    device = "/dev/disk/by-uuid/14A4A219A4A1FD7C";
    fsType = "ntfs-3g";
    options = [ "uid=1000,gid=100,forceuid,forcegid" ];
  };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp4s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
