name: check

on:
  pull_request:
  push:
    branches: [main]

jobs:
  flake-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: nix flake check
        run: nix flake check --no-build --accept-flake-config
      - name: nix fmt --check
        run: nix fmt -- --ci
